
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

      

  backend:
    build: 
      context: ./backend/project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/nest_db

  frontend:
    build: 
      context: ./frontend/project
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  pgdata:
